/**
 * The Linear credential row (docs/170, reworked by docs/248-declared-issue-trackers
 * req 4; generated by docs/308-data-driven-settings inventory.md P2, P10).
 *
 * Its declaration carries the address that stores the token, so this names no
 * path and no body field; what keeps it a component is the same slice 5 note the
 * GitHub row cites.
 *
 * **This surface holds the API token and nothing that identifies a
 * destination.** Which Linear team a repository's Issues tab shows is part of
 * that repository's own `shipit.yaml` declaration, so the team picker that used
 * to persist a deployment-wide binding is gone. The team list is a **lookup** —
 * which team keys this credential can reach — which is a property of the
 * credential and so belongs here. It is also how the row knows it is connected:
 * after docs/248 a connected credential with no declaration produces no Linear
 * tracker, so the absence of a tab is not the absence of a credential.
 */

// eslint-disable-next-line no-restricted-imports -- external system sync: which teams the stored token reaches, read once when the row appears
import { useEffect, useRef, useState } from "react";
import { Button } from "../../ui/button.js";
import { ICON_SIZE } from "../../../design-tokens.js";
import { useIssuesStore } from "../../../stores/issues-store.js";
import { settingRequest } from "../../../stores/setting-values.js";
import { settingOf } from "../setting-copy.js";
import { inputClass } from "../shared.js";
import { ConnectedServiceCard, ConnectionStatus } from "./ConnectedServiceCard.js";
import type { SettingKey } from "../../../../server/shared/settings-catalogue/index.js";

/**
 * A brand glyph is the sanctioned exception to "no hardcoded SVG" — the same one
 * `ServiceLogo.tsx` takes, for the same reason: Phosphor is a set of generic UI
 * symbols and has no vendor logos. A logo is not drawn or chosen; it is quoted.
 */
function LinearLogo() {
  return (
    <svg viewBox="0 0 100 100" width={ICON_SIZE.MD} height={ICON_SIZE.MD} fill="#5e6ad2" aria-hidden="true">
      <path d="M1.2 61.3c-.2-.8.8-1.4 1.4-.8l36 36c.6.6 0 1.6-.8 1.4A50.2 50.2 0 0 1 1.2 61.3Zm-1.1-15c0-.5.6-.8 1-.4l52 52c.4.4.1 1-.4 1a50 50 0 0 1-9.5-2.3L2.4 55.8A50 50 0 0 1 .1 46.3Zm3.4-14.7c.2-.5.8-.6 1.2-.2l64 64c.4.4.3 1-.2 1.2a50.2 50.2 0 0 1-5.6 1.9L1.6 37.2a50 50 0 0 1 1.9-5.6ZM10 19.2 80.8 90C93 81 101 66.4 101 50 101 22.4 78.6 0 51 0 34.6 0 20 8 10 19.2Z" />
    </svg>
  );
}

interface LinearTeam {
  id: string;
  key: string;
  name: string;
}

const TEAMS_PATH = "/api/trackers/linear/teams";
const DISCONNECT_PATH = "/api/trackers/linear/disconnect";

export function LinearCredential({ settingKey }: { settingKey: SettingKey }) {
  const [token, setToken] = useState("");
  const [teams, setTeams] = useState<LinearTeam[] | null>(null);
  const [connected, setConnected] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  /**
   * What the connection last learned from, so an older answer cannot describe
   * it (slice 2's rule for the own-route reads, and the same hazard here).
   *
   * The mount read takes as long as a request, and a save moves the connection
   * the moment it lands — so a read that began first and answered second would
   * put the OLD credential's teams back under a token the user has just
   * replaced, or report "not connected" over a connection that succeeded.
   * Every write bumps this, so an in-flight read is stale by construction.
   */
  const generation = useRef(0);

  const loadTeams = async () => {
    const mine = ++generation.current;
    try {
      const res = await fetch(TEAMS_PATH, { headers: { Accept: "application/json" } });
      if (generation.current !== mine) return;
      if (!res.ok) {
        setConnected(false);
        setTeams(null);
        return;
      }
      const data = (await res.json()) as { teams?: LinearTeam[] };
      if (generation.current !== mine) return;
      setConnected(true);
      setTeams(data.teams ?? []);
    } catch {
      /* ignore — the row falls back to "not connected" and its connect box */
    }
  };

  // eslint-disable-next-line no-restricted-syntax -- one-shot load of credential status when the row appears
  useEffect(() => {
    void loadTeams();
  }, []);

  /*
    The address is the declaration's, so this builds no path and no payload
    field (req 3). What it does own is the ANSWER: the teams the token reaches
    are the whole status line, and the route's `error` is the only thing that
    says why a token was refused — both of which a shared writer discards.
  */
  const connect = async () => {
    const typed = token;
    const request = settingRequest(settingOf(settingKey), typed.trim());
    if (!request) return;
    setBusy(true);
    setError(null);
    try {
      const res = await fetch(request.path, {
        method: request.method,
        headers: { "Content-Type": "application/json", Accept: "application/json" },
        body: JSON.stringify(request.body),
      });
      const data = (await res.json().catch(() => ({}))) as { error?: string; teams?: LinearTeam[] };
      if (!res.ok) {
        setError(data.error ?? "Failed to connect Linear");
        return;
      }
      generation.current += 1;
      setTeams(data.teams ?? []);
      setConnected(true);
      /*
        Only the value that was SENT is cleared: the box stays editable while
        the request is out, so one typed in since is the user's unsaved work and
        keeps what was typed — the rule slices 3 and 4 settled for every other
        write in this feature.
      */
      setToken((current) => (current === typed ? "" : current));
      void useIssuesStore.getState().fetchTrackers();
    } finally {
      setBusy(false);
    }
  };

  /*
    The answer is READ, unlike the card this replaces, which cleared the row
    whatever came back: a refused disconnect then reported "not connected" for a
    credential the server was still holding — and the row's status is the only
    thing the user has, since the token itself is never read back.
  */
  const disconnect = async () => {
    setBusy(true);
    setError(null);
    try {
      const res = await fetch(DISCONNECT_PATH, { method: "POST", headers: { Accept: "application/json" } });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      generation.current += 1;
      setConnected(false);
      setTeams(null);
      void useIssuesStore.getState().fetchTrackers();
    } catch (err) {
      setError("Failed to disconnect Linear");
      console.error("[settings] disconnecting Linear failed:", err);
    } finally {
      setBusy(false);
    }
  };

  return (
    <ConnectedServiceCard
      settingKey={settingKey}
      mark={<LinearLogo />}
      testId="settings-trackers"
      headerAction={connected ? (
        <Button
          variant="ghost"
          size="md"
          disabled={busy}
          onClick={() => { void disconnect(); }}
          data-testid="trackers-disconnect"
          aria-label="Disconnect Linear"
        >
          Disconnect
        </Button>
      ) : undefined}
    >
      {error && (
        <div className="rounded bg-(--color-error-subtle) p-2 text-xs text-(--color-error)">
          {error}
        </div>
      )}

      <ConnectionStatus
        connected={connected}
        detail={connected ? "Credential connected" : "Not connected"}
        testId="linear-status"
      />

      {connected && teams && teams.length > 0 && (
        <div className="space-y-1" data-testid="linear-connected">
          <p className="text-xs text-(--color-text-tertiary)">Teams this token can reach:</p>
          <div className="flex flex-wrap gap-1">
            {teams.map((team) => (
              <span
                key={team.id}
                title={team.name}
                className="inline-flex items-center gap-1 px-2 py-0.5 rounded border border-(--color-border-secondary) bg-(--color-bg-elevated) text-xs"
              >
                <span className="font-mono text-(--color-text-primary)">{team.key}</span>
                <span className="text-(--color-text-tertiary) truncate max-w-40">{team.name}</span>
              </span>
            ))}
          </div>
        </div>
      )}
      {connected && teams?.length === 0 && (
        <p className="text-xs text-(--color-text-tertiary)" data-testid="linear-connected">
          No teams found for this token.
        </p>
      )}

      <div className="space-y-2">
        <input
          id="linear-token"
          type="password"
          value={token}
          onChange={(e) => setToken(e.target.value)}
          placeholder="lin_api_..."
          aria-label={connected ? "Replace the Linear API token" : "Linear API token"}
          data-testid="linear-token-input"
          autoComplete="off"
          className={inputClass}
        />
        <p className="text-xs text-(--color-text-tertiary)">
          Create a personal API key in Linear → Settings → Security &amp; access → Personal API keys.
          Stored server-side and never shown again.
        </p>
        <Button
          variant="primary"
          size="md"
          disabled={busy || !token.trim()}
          onClick={() => { void connect(); }}
          aria-label={busy ? "Connecting Linear" : connected ? "Replace the Linear API token" : "Connect Linear"}
        >
          {busy ? "Connecting…" : connected ? "Replace" : "Connect Linear"}
        </Button>
      </div>
    </ConnectedServiceCard>
  );
}
