/**
 * The Linear credential row (docs/170, docs/248-declared-issue-trackers req 4;
 * generated by docs/308-data-driven-settings slice 5).
 *
 * The load-bearing assertion about this card has always been a *scope* one: it
 * is workspace-scoped, so it shows the credential and nothing that belongs to a
 * particular repository. Which team a repository's Issues tab reads is that
 * repository's own declaration. The rest is slice 5's: the write's address comes
 * from the declaration, and its answer — the teams, or the reason a token was
 * refused — is why this is a component.
 */

import { describe, it, expect, afterEach, beforeEach, vi } from "vitest";
import { act, render, screen, cleanup, fireEvent, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { LinearCredential } from "./LinearCredential.js";
import { findSetting, type SettingKey } from "../../../../server/shared/settings-catalogue/index.js";

const KEY = "integrations.linear.credential" as SettingKey;
const TEAM = { id: "t1", key: "SHI", name: "ShipIt" };

let fetchMock: ReturnType<typeof vi.fn>;

/** Answers the teams lookup; everything else answers empty and succeeds. */
function stubFetch(teams: { id: string; key: string; name: string }[] | null) {
  fetchMock = vi.fn((url: string) => {
    if (url === "/api/trackers/linear/teams") {
      return Promise.resolve(teams
        ? { ok: true, json: () => Promise.resolve({ teams }) }
        : { ok: false, json: () => Promise.resolve({ error: "Connect Linear first" }) });
    }
    return Promise.resolve({ ok: true, json: () => Promise.resolve({}) });
  });
  vi.stubGlobal("fetch", fetchMock);
  return fetchMock;
}

beforeEach(() => { stubFetch(null); });

afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
});

function paste(token: string) {
  fireEvent.change(screen.getByTestId("linear-token-input"), { target: { value: token } });
  return userEvent.click(screen.getByRole("button", { name: /Connect Linear|Replace the Linear/ }));
}

describe("the Linear credential row", () => {
  it("posts the token to the address its declaration names, under its own field", async () => {
    render(<LinearCredential settingKey={KEY} />);
    await waitFor(() => expect(screen.getByTestId("linear-status")).toBeInTheDocument());
    await paste("lin_api_abc");

    const route = findSetting(KEY)!.store as { method: string; path: string; bodyField: string };
    await waitFor(() => {
      expect(fetchMock).toHaveBeenCalledWith(route.path, expect.objectContaining({
        method: route.method,
        body: JSON.stringify({ [route.bodyField]: "lin_api_abc" }),
      }));
    });
  });

  /*
    The teams are a property of the CREDENTIAL — which team keys this token can
    reach — so the answer to the write is the status line, which a shared writer
    would have discarded.
  */
  it("shows the teams the token reaches, from the write's own answer", async () => {
    render(<LinearCredential settingKey={KEY} />);
    fetchMock.mockImplementation((url: string) =>
      Promise.resolve(url === "/api/trackers/linear/token"
        ? { ok: true, json: () => Promise.resolve({ teams: [TEAM] }) }
        : { ok: true, json: () => Promise.resolve({}) }));

    await paste("lin_api_abc");

    await waitFor(() => expect(screen.getByTestId("linear-status")).toHaveTextContent("Credential connected"));
    expect(screen.getByText("SHI")).toBeInTheDocument();
    expect(screen.getByText("ShipIt")).toBeInTheDocument();
    // The client-side follow-up that keeps the Issues tab's trackers current —
    // a credential that reaches a declared team produces a tracker.
    await waitFor(() =>
      expect(fetchMock.mock.calls.some(([url]) => url === "/api/trackers")).toBe(true));
  });

  it("says why a refused token was refused", async () => {
    render(<LinearCredential settingKey={KEY} />);
    fetchMock.mockImplementation((url: string) =>
      Promise.resolve(url === "/api/trackers/linear/token"
        ? { ok: false, json: () => Promise.resolve({ error: "Could not validate Linear token" }) }
        : { ok: true, json: () => Promise.resolve({}) }));

    await paste("nope");

    expect(await screen.findByText("Could not validate Linear token")).toBeInTheDocument();
    expect(screen.getByTestId("linear-status")).toHaveTextContent("Not connected");
  });

  it("reads the stored credential back as a connection when the row appears", async () => {
    stubFetch([TEAM]);
    render(<LinearCredential settingKey={KEY} />);

    await waitFor(() => expect(screen.getByTestId("linear-connected")).toBeInTheDocument());
    expect(screen.getByTestId("linear-status")).toHaveTextContent("Credential connected");
  });

  /*
    The box stays editable while the request is out, so a token typed in SINCE
    the save is the user's unsaved work. Clearing unconditionally erased it —
    the rule slices 3 and 4 settled for every other write in this feature.
  */
  it("clears only the token that was sent", async () => {
    render(<LinearCredential settingKey={KEY} />);
    await waitFor(() => expect(screen.getByTestId("linear-status")).toBeInTheDocument());
    let land: (() => void) | undefined;
    fetchMock.mockImplementation((url: string) =>
      url === "/api/trackers/linear/token"
        ? new Promise((resolve) => { land = () => { resolve({ ok: true, json: () => Promise.resolve({ teams: [TEAM] }) }); }; })
        : Promise.resolve({ ok: true, json: () => Promise.resolve({}) }));

    await paste("lin_api_first");
    fireEvent.change(screen.getByTestId("linear-token-input"), { target: { value: "lin_api_second" } });
    await act(async () => { land?.(); });

    expect(screen.getByTestId("linear-token-input")).toHaveValue("lin_api_second");
  });

  /*
    The mount read takes as long as a request and a save moves the connection the
    moment it lands, so a read that began first and answered second would put the
    OLD credential's teams back — or report "not connected" over a connection
    that had just succeeded.
  */
  it("discards a status read the connection moved under", async () => {
    let answerRead: (() => void) | undefined;
    fetchMock = vi.fn((url: string) => {
      if (url === "/api/trackers/linear/teams") {
        return new Promise((resolve) => { answerRead = () => { resolve({ ok: false, json: () => Promise.resolve({}) }); }; });
      }
      if (url === "/api/trackers/linear/token") {
        return Promise.resolve({ ok: true, json: () => Promise.resolve({ teams: [TEAM] }) });
      }
      return Promise.resolve({ ok: true, json: () => Promise.resolve({}) });
    });
    vi.stubGlobal("fetch", fetchMock);
    render(<LinearCredential settingKey={KEY} />);

    await paste("lin_api_abc");
    await waitFor(() => expect(screen.getByTestId("linear-status")).toHaveTextContent("Credential connected"));
    await act(async () => { answerRead?.(); });

    expect(screen.getByTestId("linear-status")).toHaveTextContent("Credential connected");
  });

  it("disconnects at an address of its own, and stops reporting a connection", async () => {
    stubFetch([TEAM]);
    render(<LinearCredential settingKey={KEY} />);
    await waitFor(() => expect(screen.getByTestId("linear-connected")).toBeInTheDocument());

    await userEvent.click(screen.getByTestId("trackers-disconnect"));

    await waitFor(() => expect(fetchMock).toHaveBeenCalledWith(
      "/api/trackers/linear/disconnect",
      expect.objectContaining({ method: "POST" }),
    ));
    expect(screen.queryByTestId("linear-connected")).toBeNull();
    expect(screen.getByTestId("linear-status")).toHaveTextContent("Not connected");
  });

  /*
    The card this replaced cleared the row whatever the route answered, so a
    refused disconnect reported "not connected" for a credential the server was
    still holding — and nothing else on screen could contradict it.
  */
  it("keeps reporting the connection when the disconnect is refused", async () => {
    vi.spyOn(console, "error").mockImplementation(() => {});
    stubFetch([TEAM]);
    render(<LinearCredential settingKey={KEY} />);
    await waitFor(() => expect(screen.getByTestId("linear-connected")).toBeInTheDocument());
    fetchMock.mockImplementation((url: string) =>
      Promise.resolve(url === "/api/trackers/linear/disconnect"
        ? { ok: false, status: 500, json: () => Promise.resolve({}) }
        : { ok: true, json: () => Promise.resolve({ teams: [TEAM] }) }));

    await userEvent.click(screen.getByTestId("trackers-disconnect"));

    expect(await screen.findByText("Failed to disconnect Linear")).toBeInTheDocument();
    expect(screen.getByTestId("linear-status")).toHaveTextContent("Credential connected");
  });

  it("shows no repository-scoped tracker declaration in workspace settings", async () => {
    stubFetch([TEAM]);
    const { container } = render(<LinearCredential settingKey={KEY} />);
    await waitFor(() => expect(screen.getByTestId("linear-connected")).toBeInTheDocument());

    expect(container.querySelector("pre")).toBeNull();
    expect(container.textContent).not.toContain("shipit.yaml");
    expect(container.textContent).not.toContain("kind: linear");
    expect(container.textContent).not.toContain("trackers:");
  });
});
