import { McpServerSettings } from "./McpServerSettings.js";
import { SshHostsSettings } from "./SshHostsSettings.js";
import { DeclaredSettings } from "./Settings/DeclaredSettings.js";

/**
 * Settings → Integrations (docs/201, generated by docs/308-data-driven-settings
 * slice 5).
 *
 * One tab for everything the user connects to ShipIt, tiered so the mechanisms
 * don't read as interchangeable:
 *
 *  1. **Connected services** — curated first-party integrations (GitHub,
 *     Linear). Credentials are brokered by ShipIt and never enter the session
 *     container; their data renders inline in chat. Badged "Managed by ShipIt".
 *  2. **SSH hosts** — also brokered and also never in the container, but a list
 *     the user maintains rather than one connection (docs/305).
 *  3. **MCP servers** — user-supplied tool extensions via the Model Context
 *     Protocol. These run with whatever credentials the user provides.
 *
 * The first tier's two rows and the auto-create-PR row above them are
 * **generated**: their order, their sections and their words come from the
 * catalogue, and the two credentials through components that own operations a
 * value writer has no shape for. The two panels below are still hand-written —
 * registering them is slice 6 (inventory.md P18), and until then this file
 * places them.
 *
 * **Auto-create-PR is above the connection it depends on**, which is where its
 * declaration is: it is a payload setting in `global-settings.ts`, the first
 * source in the catalogue registry, and moving it out would change the derived
 * `GlobalSettings` types. Requirement 11 takes the order that falls out — and
 * the row is now visible while GitHub is disconnected, which is P13 and
 * requirement 4: a setting that cannot take effect yet is not hidden.
 *
 * The split closes the discoverability gap that sent users hunting for a Linear
 * MCP (which would bypass the `shipit issue` brokering): Linear sits right next
 * to GitHub, visibly *not* an MCP. See docs/190 for the removal of the duplicate
 * Linear MCP OAuth preset this builds on.
 */

function SectionHeader({ title, hint, description }: { title: string; hint: string; description: string }) {
  return (
    <div>
      <div className="flex items-baseline gap-2">
        <h3 className="text-sm font-semibold text-(--color-text-primary)">{title}</h3>
        <span className="text-xs text-(--color-text-tertiary)">· {hint}</span>
      </div>
      <p className="mt-1 text-xs text-(--color-text-secondary)">{description}</p>
    </div>
  );
}

export function SettingsIntegrations({ hasActiveSession }: { hasActiveSession: boolean }) {
  return (
    <div className="flex h-full flex-col gap-6 overflow-y-auto px-5 py-4" data-testid="settings-integrations">
      <DeclaredSettings
        tab="integrations"
        notes={{
          "Connected services": (
            <p className="text-xs text-(--color-text-secondary)">
              Managed by ShipIt. Credentials are brokered and never enter the session container;
              their data renders inline in chat.
            </p>
          ),
        }}
      />

      <div className="h-px bg-(--color-border-secondary)" />

      {/* docs/305 — a list the user maintains rather than one connection, so it
          gets its own section beside GitHub and Linear rather than a card among
          them. Its declarations are the SSH panel's; slice 6 registers it. */}
      <section className="flex flex-col gap-3">
        <SectionHeader
          title="SSH hosts"
          hint="managed by ShipIt"
          description="Servers a session can reach over SSH. ShipIt generates a key per destination, holds the private half, and signs for it — the agent never reads it. Grant a destination to a session in that session's settings."
        />
        <SshHostsSettings />
      </section>

      <div className="h-px bg-(--color-border-secondary)" />

      {/* Tier 3 — user-supplied tools, bring-your-own-credentials */}
      <section className="flex flex-col gap-3">
        <SectionHeader
          title="MCP servers"
          hint="bring your own tools"
          description="Extend the agent with your own tools via the Model Context Protocol. These run with the credentials you provide."
        />
        <McpServerSettings hasActiveSession={hasActiveSession} embedded />
      </section>
    </div>
  );
}
