import { DeclaredSettings } from "./Settings/DeclaredSettings.js";

/**
 * Settings → Integrations (docs/201, generated by docs/308-data-driven-settings
 * slices 5 and 6).
 *
 * One tab for everything the user connects to ShipIt, tiered so the mechanisms
 * don't read as interchangeable:
 *
 *  1. **Connected services** — curated first-party integrations (GitHub,
 *     Linear). Credentials are brokered by ShipIt and never enter the session
 *     container; their data renders inline in chat. Badged "Managed by ShipIt".
 *  2. **SSH hosts** — also brokered and also never in the container, but a list
 *     the user maintains rather than one connection (docs/305).
 *  3. **MCP servers** — user-supplied tool extensions via the Model Context
 *     Protocol. These run with whatever credentials the user provides.
 *
 * **Every row above is generated**, panels included: the two credentials and the
 * two list editors are components their declarations name, and the tiering is
 * declaration order in `integrations-settings.ts` rather than a layout written
 * here (req 11). What is left is this note — prose belonging to a section rather
 * than to any one setting (inventory.md P12).
 *
 * **Auto-create-PR is not on this tab.** It led it for one release, above the
 * connection it depends on, and it now sits in Advanced → Automation with the
 * other things ShipIt does to a pull request unasked. It is still visible with
 * GitHub disconnected, which is P13 and requirement 4.
 *
 * The split closes the discoverability gap that sent users hunting for a Linear
 * MCP (which would bypass the `shipit issue` brokering): Linear sits right next
 * to GitHub, visibly *not* an MCP. See docs/190 for the removal of the duplicate
 * Linear MCP OAuth preset this builds on.
 */
export function SettingsIntegrations() {
  return (
    <div className="flex h-full flex-col gap-6 overflow-y-auto px-5 py-4" data-testid="settings-integrations">
      <DeclaredSettings
        tab="integrations"
        notes={{
          "Connected services": (
            <p className="text-xs text-(--color-text-secondary)">
              Managed by ShipIt. Credentials are brokered and never enter the session container;
              their data renders inline in chat.
            </p>
          ),
        }}
      />
    </div>
  );
}
