export const CLAUDE_TOOL_NAMES = [
  "Agent",
  "AskUserQuestion",
  "Bash",
  "CronCreate",
  "CronDelete",
  "CronList",
  "Edit",
  "EnterPlanMode",
  "EnterWorktree",
  "ExitPlanMode",
  "ExitWorktree",
  "Glob",
  "Grep",
  "ListMcpResourcesTool",
  "LSP",
  "Monitor",
  "NotebookEdit",
  "PowerShell",
  "PushNotification",
  "Read",
  "ReadMcpResourceTool",
  "RemoteTrigger",
  "ScheduleWakeup",
  "SendMessage",
  "ShareOnboardingGuide",
  "Skill",
  "TaskCreate",
  "TaskGet",
  "TaskList",
  "TaskOutput",
  "TaskStop",
  "TaskUpdate",
  "TeamCreate",
  "TeamDelete",
  "TodoWrite",
  "ToolSearch",
  "WaitForMcpServers",
  "WebFetch",
  "WebSearch",
  "Workflow",
  "Write",
] as const;

export const OPENCODE_TOOL_NAMES = [
  "bash",
  "edit",
  "glob",
  "grep",
  "read",
  "skill",
  "task",
  "todowrite",
  "webfetch",
  "write",
] as const;

export const GROK_TOOL_NAMES = [
  "ask_user_question",
  "enter_plan_mode",
  "exit_plan_mode",
  "get_command_or_subagent_output",
  "grep",
  "image_edit",
  "image_gen",
  "image_to_video",
  "kill_command_or_subagent",
  "list_dir",
  "monitor",
  "read_file",
  "reference_to_video",
  "run_terminal_command",
  "scheduler_create",
  "scheduler_delete",
  "scheduler_list",
  "search_replace",
  "search_tool",
  "spawn_subagent",
  "todo_write",
  "use_tool",
  "web_search",
  "workflow",
  "write",
] as const;

// The 57 names in the CLI's own `init.tools`, captured on 1.2.2
// (docs/301-antigravity-harness/probes/flash-test.ndjson). MCP servers do not
// appear here: every MCP call goes through the `call_mcp_tool` wrapper.
export const ANTIGRAVITY_TOOL_NAMES = [
  "ask_custom_permission",
  "ask_permission",
  "ask_question",
  "browser_click_element",
  "browser_drag_pixel_to_pixel",
  "browser_get_dom",
  "browser_get_network_request",
  "browser_input",
  "browser_list_network_requests",
  "browser_mouse_down",
  "browser_mouse_up",
  "browser_move_mouse",
  "browser_press_key",
  "browser_refresh_page",
  "browser_resize_window",
  "browser_scroll",
  "browser_scroll_dom",
  "browser_select_option",
  "browser_subagent",
  "call_mcp_tool",
  "capture_browser_console_logs",
  "capture_browser_screenshot",
  "click_browser_pixel",
  "command_status",
  "define_subagent",
  "delete_knowledge",
  "execute_browser_javascript",
  "find_by_name",
  "finish",
  "generate_image",
  "grep_search",
  "invoke_subagent",
  "list_browser_pages",
  "list_dir",
  "list_permissions",
  "list_resources",
  "manage_inbox",
  "manage_subagents",
  "manage_task",
  "multi_replace_file_content",
  "notebook_edit",
  "notebook_execution",
  "open_browser_url",
  "read_browser_page",
  "read_resource",
  "read_url_content",
  "replace_file_content",
  "run_command",
  "schedule",
  "search_web",
  "sed_file",
  "send_command_input",
  "send_message",
  "view_file",
  "wait",
  "wait_5_seconds",
  "write_to_file",
] as const;

export const CODEX_TOOL_NAMES = [
  "shell",
  "commandExecution",
  "fileChange",
  "apply_patch",
  "mcpToolCall",
  "dynamicToolCall",
  "collabToolCall",
  "spawn_agent",
  "Agent",
  "wait",
  "closeAgent",
  "webSearch",
  "imageView",
  "view_image",
  "tool_search",
  "AskUserQuestion",
] as const;
