export const CLAUDE_TOOL_NAMES = [
  "Agent",
  "AskUserQuestion",
  "Bash",
  "CronCreate",
  "CronDelete",
  "CronList",
  "Edit",
  "EnterPlanMode",
  "EnterWorktree",
  "ExitPlanMode",
  "ExitWorktree",
  "Glob",
  "Grep",
  "ListMcpResourcesTool",
  "LSP",
  "Monitor",
  "NotebookEdit",
  "PowerShell",
  "PushNotification",
  "Read",
  "ReadMcpResourceTool",
  "RemoteTrigger",
  "ScheduleWakeup",
  "SendMessage",
  "ShareOnboardingGuide",
  "Skill",
  "TaskCreate",
  "TaskGet",
  "TaskList",
  "TaskOutput",
  "TaskStop",
  "TaskUpdate",
  "TeamCreate",
  "TeamDelete",
  "TodoWrite",
  "ToolSearch",
  "WaitForMcpServers",
  "WebFetch",
  "WebSearch",
  "Workflow",
  "Write",
] as const;

export const OPENCODE_TOOL_NAMES = [
  "bash",
  "edit",
  "glob",
  "grep",
  "read",
  "skill",
  "task",
  "todowrite",
  "webfetch",
  "write",
] as const;

export const GROK_TOOL_NAMES = [
  "ask_user_question",
  "enter_plan_mode",
  "exit_plan_mode",
  "get_command_or_subagent_output",
  "grep",
  "image_edit",
  "image_gen",
  "image_to_video",
  "kill_command_or_subagent",
  "list_dir",
  "monitor",
  "read_file",
  "reference_to_video",
  "run_terminal_command",
  "scheduler_create",
  "scheduler_delete",
  "scheduler_list",
  "search_replace",
  "search_tool",
  "spawn_subagent",
  "todo_write",
  "use_tool",
  "web_search",
  "workflow",
  "write",
] as const;

export const CODEX_TOOL_NAMES = [
  "shell",
  "commandExecution",
  "fileChange",
  "apply_patch",
  "mcpToolCall",
  "dynamicToolCall",
  "collabToolCall",
  "spawn_agent",
  "Agent",
  "wait",
  "closeAgent",
  "webSearch",
  "imageView",
  "view_image",
  "tool_search",
  "AskUserQuestion",
] as const;
