#!/usr/bin/env bash
# Sourced helpers for local install, update, and stop scripts.

SHIPIT_HOME="${SHIPIT_HOME:-$HOME/.shipit}"
COMPOSE_FILE="$SHIPIT_HOME/docker/local/prod/compose.yml"
CHANNEL_FILE="$SHIPIT_HOME/.release-channel"
COMPOSE_STACK="shipit-prod"

shipit_channel_ref() {
  local channel
  channel="$(cat "$CHANNEL_FILE" 2>/dev/null || echo stable)"
  case "$channel" in
    stable)
      if git -C "$SHIPIT_HOME" ls-remote --exit-code --heads origin stable >/dev/null 2>&1; then
        echo "origin/stable"
      else
        echo "origin/main"
      fi
      ;;
    edge)
      echo "origin/main"
      ;;
    *)
      echo "Error: invalid release channel '$channel' in $CHANNEL_FILE (expected 'stable' or 'edge')." >&2
      return 1
      ;;
  esac
}

# Ignore untracked operator state because reset --hard does not remove it.
shipit_sync_checkout() {
  if [ -n "$(git -C "$SHIPIT_HOME" status --porcelain --untracked-files=no)" ]; then
    echo "Error: $SHIPIT_HOME has uncommitted changes to tracked files; commit, stash, or discard them first." >&2
    return 1
  fi
  local ref channel
  ref="$(shipit_channel_ref)" || return 1
  channel="$(cat "$CHANNEL_FILE" 2>/dev/null || echo stable)"
  echo "==> Syncing $SHIPIT_HOME to channel '$channel' (ref $ref)..."
  git -C "$SHIPIT_HOME" fetch origin --tags --prune
  git -C "$SHIPIT_HOME" fetch origin "${ref#origin/}"
  git -C "$SHIPIT_HOME" reset --hard "$ref"
}

SHIPIT_ENV_FILE="${SHIPIT_ENV_FILE:-$SHIPIT_HOME/.shipit.env}"

TAILNET_COMPOSE_FILE="${TAILNET_COMPOSE_FILE:-$SHIPIT_HOME/.shipit-tailnet.compose.yml}"

# BSD sed requires a suffix for -i.
shipit_persist_env() {
  local key="$1" value="$2"
  mkdir -p "$(dirname "$SHIPIT_ENV_FILE")"
  touch "$SHIPIT_ENV_FILE"
  chmod 600 "$SHIPIT_ENV_FILE"
  if grep -q "^${key}=" "$SHIPIT_ENV_FILE" 2>/dev/null; then
    sed -i.bak "s|^${key}=.*|${key}=${value}|" "$SHIPIT_ENV_FILE" && rm -f "$SHIPIT_ENV_FILE.bak"
  else
    echo "${key}=${value}" >> "$SHIPIT_ENV_FILE"
  fi
}

shipit_load_env_file() {
  if [ -f "$SHIPIT_ENV_FILE" ]; then
    set -a
    # shellcheck source=/dev/null
    . "$SHIPIT_ENV_FILE"
    set +a
  fi
}

# The macOS app keeps its CLI inside the application bundle.
shipit_tailscale_bin() {
  if [ -n "${SHIPIT_TAILSCALE_BIN:-}" ]; then
    [ -x "$SHIPIT_TAILSCALE_BIN" ] || return 1
    printf '%s\n' "$SHIPIT_TAILSCALE_BIN"
    return 0
  fi
  if command -v tailscale >/dev/null 2>&1; then
    printf 'tailscale\n'
    return 0
  fi
  local prefix="${SHIPIT_TAILSCALE_PREFIX:-}" candidate
  for candidate in \
    "$prefix/Applications/Tailscale.app/Contents/MacOS/Tailscale" \
    "$prefix/usr/local/bin/tailscale" \
    "$prefix/opt/homebrew/bin/tailscale"; do
    if [ -x "$candidate" ]; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done
  return 1
}

# Recompute the optional tailnet binding before each start. Failures fall back to loopback.
shipit_refresh_tailnet_bind() {
  if [ "${SHIPIT_TAILNET_BIND:-}" != "1" ]; then
    shipit_drop_tailnet_overlay
    return 0
  fi

  # Disconnected Tailscale must not trip callers' `set -e`.
  local ts_ip="" ts_bin=""
  ts_bin="$(shipit_tailscale_bin || true)"
  if [ -n "$ts_bin" ]; then
    ts_ip="$("$ts_bin" ip -4 2>/dev/null | head -n1 || true)"
  fi

  if [ -z "$ts_ip" ]; then
    shipit_drop_tailnet_overlay
    echo "==> Tailscale not reachable; starting on localhost only." >&2
    echo "    Re-run this start (update.sh) once Tailscale is up to restore tailnet access." >&2
    return 0
  fi

  # Write atomically; the overlay adds a binding without replacing loopback.
  local tmp=""
  tmp="$(mktemp "${TAILNET_COMPOSE_FILE}.XXXXXX" 2>/dev/null || true)"
  if [ -z "$tmp" ]; then
    shipit_drop_tailnet_overlay
    echo "==> Could not write the tailnet overlay; starting on localhost only." >&2
    return 0
  fi
  if ! cat > "$tmp" <<EOF
# GENERATED by deployment/local/lib.sh — do not edit, rewritten on every start.
# Opt-in tailnet binding for the local install (docs/254). Remove
# SHIPIT_TAILNET_BIND from $SHIPIT_ENV_FILE to opt out.
services:
  shipit:
    ports:
      - "${ts_ip}:4123:4123"
EOF
  then
    rm -f "$tmp" 2>/dev/null || true
    shipit_drop_tailnet_overlay
    echo "==> Could not write the tailnet overlay; starting on localhost only." >&2
    return 0
  fi
  if ! mv -f "$tmp" "$TAILNET_COMPOSE_FILE" 2>/dev/null; then
    rm -f "$tmp" 2>/dev/null || true
    shipit_drop_tailnet_overlay
    echo "==> Could not write the tailnet overlay; starting on localhost only." >&2
    return 0
  fi
  SHIPIT_TAILNET_IP="$ts_ip"
}

# A stale overlay remains active, so report removal failures.
shipit_drop_tailnet_overlay() {
  [ -e "$TAILNET_COMPOSE_FILE" ] || return 0
  if ! rm -f "$TAILNET_COMPOSE_FILE" 2>/dev/null; then
    echo "==> Warning: could not remove $TAILNET_COMPOSE_FILE." >&2
    echo "    ShipIt will keep using the tailnet binding it contains until it is deleted." >&2
  fi
  return 0
}

shipit_compose_files() {
  printf '%s\n' -f "$COMPOSE_FILE"
  if [ -f "$TAILNET_COMPOSE_FILE" ]; then
    printf '%s\n' -f "$TAILNET_COMPOSE_FILE"
  fi
}

shipit_build_and_up() {
  shipit_load_env_file
  shipit_refresh_tailnet_bind
  local compose_files=()
  while IFS= read -r arg; do compose_files+=("$arg"); done < <(shipit_compose_files)
  echo "==> Building ShipIt images..."
  docker compose "${compose_files[@]}" build --pull session-worker shipit egress-sidecar
  echo "==> Starting ShipIt (detached)..."
  docker compose "${compose_files[@]}" up -d --no-build shipit
}

shipit_cleanup_sessions() {
  # shellcheck disable=SC2046  # intentional word-splitting over the id list
  docker rm -f $(docker ps -aq --filter "label=shipit-parent-session") 2>/dev/null || true
  # shellcheck disable=SC2046
  docker rm -f $(docker ps -aq --filter "label=shipit-stack=$COMPOSE_STACK") 2>/dev/null || true
  docker network prune -f >/dev/null 2>&1 || true
}
