import { normalizeHost } from "./egress-allowlist.js";

export const EGRESS_IPSET_V4 = "shipit-egress-allow4";
export const EGRESS_IPSET_V6 = "shipit-egress-allow6";

// Firewall owner matching permits upstream DNS only for this UID; it must differ from the agent.
export const EGRESS_RESOLVER_UID = 911;
export const EGRESS_RESOLVER_USER = "egressdns";

export const EGRESS_RESOLVER_LISTEN = "127.0.0.1";

export const DOCKER_EMBEDDED_DNS = "127.0.0.11";

export function allowlistEntryToDomain(entry: string): string {
  const h = normalizeHost(entry);
  return h.startsWith(".") ? h.slice(1) : h;
}

export interface DnsmasqConfigOpts {
  /** dnsmasq also matches subdomains, including for exact allowlist entries. */
  publicDomains: string[];
  publicUpstreams: string[];
  internalDomains?: string[];
  unqualifiedInternalNames?: boolean;
  ipsetV4?: string;
  ipsetV6?: string;
  resolverUser?: string;
  listenAddress?: string;
  dockerDns?: string;
}

export function buildDnsmasqConfig(opts: DnsmasqConfigOpts): string {
  const ipsetV4 = opts.ipsetV4 ?? EGRESS_IPSET_V4;
  const ipsetV6 = opts.ipsetV6 ?? EGRESS_IPSET_V6;
  const user = opts.resolverUser ?? EGRESS_RESOLVER_USER;
  const listen = opts.listenAddress ?? EGRESS_RESOLVER_LISTEN;
  const dockerDns = opts.dockerDns ?? DOCKER_EMBEDDED_DNS;

  const publicDomains = dedupe(opts.publicDomains.map(allowlistEntryToDomain).filter(Boolean));
  const internalDomains = dedupe((opts.internalDomains ?? []).map(normalizeHost).filter(Boolean));
  const upstreams = opts.publicUpstreams.filter(Boolean);
  if (upstreams.length === 0) throw new Error("buildDnsmasqConfig: at least one public upstream is required");

  const lines: string[] = [
    "# Generated by ShipIt egress Tier B (docs/172 Gap 1, planning#92). Do not edit.",
    "no-resolv",
    "no-hosts",
    "bind-interfaces",
    `listen-address=${listen}`,
    "port=53",
    `user=${user}`,
    "cache-size=1000",
    "",
    "# Allowlisted PUBLIC domains: forward to the upstream AND pin resolved IPs",
    "# into the egress firewall ipset (resolve-and-pin → no stale-IP breakage).",
  ];
  for (const domain of publicDomains) {
    for (const up of upstreams) lines.push(`server=/${domain}/${up}`);
    lines.push(`ipset=/${domain}/${ipsetV4},${ipsetV6}`);
  }
  if (internalDomains.length > 0 || opts.unqualifiedInternalNames) {
    lines.push("", "# Internal names → Docker embedded DNS (reached by IP via the bridge allow).");
    // Do not emit repo service names as domains: a name like com would allow *.com.
    if (opts.unqualifiedInternalNames) lines.push(`server=//${dockerDns}`);
    for (const domain of internalDomains) lines.push(`server=/${domain}/${dockerDns}`);
  }
  lines.push(
    "",
    "# No default server: any name matching neither list is REFUSED — this is",
    "# what closes DNS-tunneling exfil (the query is never forwarded anywhere).",
    "",
  );
  return lines.join("\n");
}

function dedupe(xs: string[]): string[] {
  return [...new Set(xs)];
}
