/**
 * Secret resolver — resolves declared `x-shipit-secrets` from the compose file
 * against user-saved secrets (SecretStore) and writes per-service env files
 * that the compose override references via `env_file:`.
 *
 * Phase 1 (this module):
 *   - Simple string form only (`x-shipit-secrets: [STRIPE_KEY, ...]`)
 *   - Values come from the user's SecretStore for the session's repo URL
 *   - Output: `.shipit/.env.<service>` files per service that declared secrets
 *
 * Later phases extend this module to:
 *   - Object-form entries with `description`, `required`, `agent`, `source`
 *   - Platform credential resolution (`source: platform:claude_oauth`, etc.)
 *   - Agent container env file (`.shipit/.env.agent`) for `agent: true` entries
 *   - Docker secrets-based delivery instead of env files for stronger isolation
 *
 * The output is intentionally minimal and predictable — sorted keys, single
 * quoting only when required — so writes are deterministic and don't trigger
 * unnecessary container recreations from compose.
 */

import fs from "node:fs";
import path from "node:path";
import type { ComposeService } from "./compose-generator.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface SecretResolution {
  /** Per-service env-file contents, keyed by service name. */
  perServiceEnv: Record<string, string>;
  /** Service-name → list of secret names declared but not present in user secrets. */
  missingByService: Record<string, string[]>;
  /** All secret names referenced by any service. */
  declaredNames: string[];
}

// ---------------------------------------------------------------------------
// Resolution
// ---------------------------------------------------------------------------

/**
 * Resolve declared secrets from `x-shipit-secrets` against user-saved secrets.
 *
 * Returns a per-service env-file body for every service that declares at least
 * one secret. Services with no declarations get no entry (compose override
 * also skips `env_file:` for them).
 *
 * Missing secrets are reported per service but do not cause a failure — they
 * become validation surface for Phase 2 (`required: true` warnings).
 */
export function resolveSecrets(opts: {
  services: ComposeService[];
  userSecrets: Record<string, string>;
}): SecretResolution {
  const { services, userSecrets } = opts;
  const perServiceEnv: Record<string, string> = {};
  const missingByService: Record<string, string[]> = {};
  const declaredNames = new Set<string>();

  for (const svc of services) {
    if (!svc.secrets || svc.secrets.length === 0) continue;

    // De-duplicate within a service in case the user repeats a name
    const unique = [...new Set(svc.secrets)];
    const present: { key: string; value: string }[] = [];
    const missing: string[] = [];

    for (const name of unique) {
      declaredNames.add(name);
      const value = userSecrets[name];
      if (typeof value === "string" && value.length > 0) {
        present.push({ key: name, value });
      } else {
        missing.push(name);
      }
    }

    if (missing.length > 0) {
      missingByService[svc.name] = missing;
    }

    perServiceEnv[svc.name] = renderEnvFile(present);
  }

  return {
    perServiceEnv,
    missingByService,
    declaredNames: [...declaredNames].sort(),
  };
}

/**
 * Render a list of key/value pairs into a docker-compose-compatible env file.
 *
 * Format rules:
 *   - One `KEY=VALUE` per line.
 *   - Keys are sorted alphabetically for deterministic output.
 *   - Values containing newlines are rejected — compose `env_file` cannot
 *     express them and the agent should not store multi-line values.
 *   - All other values are written verbatim. Compose's env-file parser does
 *     NOT interpret quotes — leading/trailing quotes become part of the value
 *     — so we must pass the raw string. Any character (including `#`, `"`,
 *     `'`, spaces, `=`) is preserved as-is.
 *   - A leading "# Generated by ShipIt" header makes the file recognizable.
 */
function renderEnvFile(entries: { key: string; value: string }[]): string {
  const sorted = [...entries].sort((a, b) => a.key.localeCompare(b.key));
  const lines: string[] = [
    "# Generated by ShipIt — do not edit manually.",
    "# This file holds secrets for a single compose service. Rewritten on every",
    "# session activation and on PUT /api/secrets.",
  ];
  for (const { key, value } of sorted) {
    if (value.includes("\n") || value.includes("\r")) {
      // Skip multi-line values — compose's env_file parser doesn't support them.
      // The user can still reach them through the secrets API but they won't
      // be exposed to compose services. (Phase 2 surfaces this as a warning.)
      continue;
    }
    lines.push(`${key}=${value}`);
  }
  // Trailing newline so the file ends cleanly.
  return `${lines.join("\n")}\n`;
}

// ---------------------------------------------------------------------------
// Filesystem
// ---------------------------------------------------------------------------

/**
 * Write per-service env files to `.shipit/.env.<service>` inside `workspaceDir`.
 *
 * - Creates the `.shipit/` directory if missing.
 * - Files are written with mode 0600 (the workspace volume is shared with the
 *   agent — file mode is a defense-in-depth measure but does not prevent
 *   process.env exfiltration through agent-authored code; see plan §"Security").
 * - Stale `.shipit/.env.<svc>` files for services that no longer declare
 *   secrets (or were removed from compose) are deleted, so a service can't
 *   re-pick up a leftover file from a previous compose definition.
 *
 * Returns the list of file paths written (relative to `workspaceDir`).
 */
export function writePerServiceEnvFiles(opts: {
  workspaceDir: string;
  perServiceEnv: Record<string, string>;
}): string[] {
  const { workspaceDir, perServiceEnv } = opts;
  const shipitDir = path.join(workspaceDir, ".shipit");
  fs.mkdirSync(shipitDir, { recursive: true });

  // Remove stale `.env.<svc>` files for services that no longer declare secrets.
  // We only sweep files we own (the `.env.` prefix) and leave `.env.agent`
  // alone (Phase 3 owns it).
  let existing: string[] = [];
  try {
    existing = fs.readdirSync(shipitDir);
  } catch {
    existing = [];
  }
  const keep = new Set<string>();
  for (const svc of Object.keys(perServiceEnv)) keep.add(`.env.${svc}`);
  for (const entry of existing) {
    if (!entry.startsWith(".env.")) continue;
    if (entry === ".env.agent") continue; // Phase 3 owns this
    if (keep.has(entry)) continue;
    try {
      fs.unlinkSync(path.join(shipitDir, entry));
    } catch {
      // Best-effort cleanup
    }
  }

  const written: string[] = [];
  for (const [serviceName, body] of Object.entries(perServiceEnv)) {
    const filePath = path.join(shipitDir, `.env.${serviceName}`);
    fs.writeFileSync(filePath, body, { mode: 0o600 });
    written.push(path.relative(workspaceDir, filePath));
  }
  return written;
}
