name: Pull request labeler

on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    name: Label PR by changed paths
    # Do not give pull_request_target write access to external branches.
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/labeler@v6.1.0
        continue-on-error: true
        with:
          repo-token: ${{ github.token }}
          configuration-path: .github/labeler.yml
          sync-labels: false
          dot: true
